### PR TITLE
Remove lerna package

### PR DESCRIPTION
**Pull request by enBonnet**
Lerna doesn't seem to be in use.

What do you think? @KATT

### CODE REVIEW

**Comment by KATT** [comment]
It's definitely used.

**Comment by enBonnet** [comment]
How do you use it? I don't get it sorry.

Now that Lerna is out of support is possible to replace it with turborepo or something like that?

**Comment by KATT** [comment]
Yes, that is possible, but it's still used as of now.

**Comment by KATT** [comment]
Ooops, I thought this was on the trpc repo. Unsure if it's used here.

**Comment by enBonnet** [comment]
I was looking and I didn't find any use of Lerna here, because all the scripts that we run use `npm-run-all` instead of Lerna.

In my project after deleting Lerna, everything seems to be working well

**Comment by enBonnet** [comment]
Let me know if I can help you with something else

**Pull request closed without merging**
